# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
