# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180610_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='id',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='codigo_da_consulta',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
