# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180610_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='codigo_da_consulta',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
